notifications:
  commits:      commits@infra.apache.org
  pullrequests: commits@infra.apache.org
  issues:       users@infra.apache.org
github:
  protected_branches:
    master:
      required_status_checks:
        strict: true
        contexts:
          - gh-infra/jenkins
          - foobar
 
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 3
      required_linear_history: true
      required_signatures: true
  del_branch_on_merge: true
