notifications:
  commits:      commits@infra.apache.org
  pullrequests: commits@infra.apache.org
  issues:       users@infra.apache.org
github:
  protected_branches:
    master:
      required_status_checks:
        strict: true
 
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
 
      required_signatures: true
  
