name: Puppet Lint

on: [push]

jobs:
  puppet-lint:

    runs-on: asf-runner
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: puppet-lint
      uses: scottbrenner/puppet-lint-action@master
      with:
        args: ./
